###
## Version Information
###
set ( HPCC_CONFIGURATOR_MAJOR 5 )
set ( HPCC_CONFIGURATOR_MINOR 1 )
set ( HPCC_CONFIGURATOR_POINT 0 )
set ( HPCC_CONFIGURATOR_MATURITY "trunk" )
set ( HPCC_CONFIGURATOR_SEQUENCE 0 )
###
